"""empty message

Revision ID: 497717b6e15c
Revises: 
Create Date: 2024-04-18 19:24:56.284543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497717b6e15c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cp_clients_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('cp_clients_stages_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cp_contracts_import', ['import_id'], ['id'])
        batch_op.create_foreign_key(None, 'cp_users', ['client_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('load_file_name')

    with op.batch_alter_table('cp_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contrato', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('indice', sa.Integer(), nullable=True))
        batch_op.drop_column('contract_code')

    with op.batch_alter_table('cp_contracts_import', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.drop_column('input_file_name')

    with op.batch_alter_table('cp_contracts_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('load_file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cp_contracts_stage', schema=None) as batch_op:
        batch_op.drop_column('import_id')
        batch_op.drop_column('load_file_name')

    with op.batch_alter_table('cp_contracts_import', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('cp_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('indice')
        batch_op.drop_column('contrato')
        batch_op.drop_column('cpf_cnpj')
        batch_op.drop_column('nome')
        batch_op.drop_column('chave')

    with op.batch_alter_table('cp_clients_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('load_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cp_clients_stages_user_id_fkey', 'cp_users', ['user_id'], ['id'])
        batch_op.drop_column('client_id')
        batch_op.drop_column('import_id')

    # ### end Alembic commands ###
